# The host you want to upload to.
# Possible values are "punpun.xyz" (for now).
host = "punpun.xyz"

# Your authentication key.
key = "seekrit"

# Your preferred screenshot command.
# Make sure to save the file to /tmp/screenshot.png.
scrot = "maim -q 5 -o /tmp/screenshot.png"

# Your preferred selection screenshot command.
# Make sure to save the file to /tmp/screenshot.png.
selscrot = "maim -b 1 -c 0.921,0.376,0.517,1 -s -q 5 -o /tmp/screenshot.png"

# Copy URL to clipboard.
clipboard = true

# Log URL to file.
log = true

# Print URL to stdout.
print = true
