complete -c punf -f -o c -l clipboard -d 'upload your clipboard as text'
complete -c punf -f -o l -l list -d 'list all uploaded files'
complete -c punf -f -o s -l selection -d 'upload selection scrot'
complete -c punf -o q -l quiet -d 'disable all feedback'
complete -c punf -f -o h -l help -d 'print help and exit'
