#!/bin/fish

# Set default host (punpun.xyz or sr.ht)
set host sr.ht

# Your sr.ht/punpun.xyz key
set key (cat $HOME/.$host ^/dev/null)

# Log urls
set log true

# Copy links to clipboard
set clipboard true

# Send notification when upload is done (requires my notify script)
set notify true

# Open url in browser
set browser false
