complete -c punf -f -o c -l clipboard -d 'upload your clipboard as text'
complete -c neet -f -o d -l desktop -d 'force desktop scrot'
complete -c neet -f -o s -l selection -d 'upload selection scrot'
complete -c neet -o q -l quiet -d 'disable all feedback'
complete -c neet -f -o h -l help -d 'print help and exit'
